### ISSUE TITLE
Close menú after click on any item

### ISSUE THREAD

**Issue by IvanLopezLuna** [vtex-apps/mega-menu#1]
**What are you trying to accomplish? Please describe.**
Is there any prop to configure the mega-menu to close after the user clicks on any item and is redirected to the search result
Currently, the only way to close the menu is by clicking outside the menu.

**What have you tried so far?**
I tried to look for directly on the compoments but I could not find something.

**Additional info**
[Example](https://featurenavmegamenu--martimxlite.myvtex.com/)

| Account        | Workspace        |
| -------------- | ---------------- |
| `martimxlite` | `featurenavmegamenu` |

![Screenshot_20211018-140123](https://user-images.githubusercontent.com/23274114/137791003-8e50c1f3-59ad-466a-8774-7546878ca0e7.jpg)

**Comment by ejisselgb** [comment]
Hi @IvanLopezLuna, in the new version 2.0.5, the bug was closed. I added the functionality to close the menu after the user clicks on any item or is redirected to the search result. If the app doesn't update automatically from the housekeeper, execute the command:  `vtex update`. If your problem persists, please, let me know.
